Update deployment.yml

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -10,15 +10,15 @@ jobs:
   validation:
       name: Branch validation
       runs-on: ubuntu-latest
-    steps:
-      - name: Check branch name
-        run: |
-          if [[ "${{ github.ref }}" == "refs/heads/main" ]] || [[ "${{ github.ref }}" =~ ^refs/heads/feature/.*$ ]] || [[ "${{ github.ref }}" =~ ^refs/heads/bug/.*$ ]] ; then
-            echo "Branch naming is correct!"
-          else
-            echo "Invalid branch name! Correct format: 'feature/<branch-name>' or 'bug/<branch-name>'"
-            exit 1
-          fi
+      steps:
+        - name: Check branch name
+          run: |
+            if [[ "${{ github.ref }}" == "refs/heads/main" ]] || [[ "${{ github.ref }}" =~ ^refs/heads/feature/.*$ ]] || [[ "${{ github.ref }}" =~ ^refs/heads/bug/.*$ ]] ; then
+              echo "Branch naming is correct!"
+            else
+              echo "Invalid branch name! Correct format: 'feature/<branch-name>' or 'bug/<branch-name>'"
+              exit 1
+            fi
   build:
     name: build
     needs: validation
