Update deployment.yml

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -7,6 +7,18 @@ on:
   workflow_dispatch:
 
 jobs:
+  validation:
+      name: Branch validation
+      runs-on: ubuntu-latest
+      steps:
+      - name: Check branch name
+        run: |
+          if [[ "${{ github.head_ref }}" == feature/* ]]; then
+            echo "Branch naming is correct!"
+          else
+            echo "Invalid branch name! Correct format: feature/<branch-name>"
+            exit 1
+          fi
   build:
     name: build
     runs-on: ubuntu-latest
